mode: debug
port: :8080
app-name: collector-sidecar-server
url: http://127.0.0.1:8080
max-ping-count: 10
jwt-secret: 1234567890
language: zh

database:
  enable: true
  auto-migrate: true
  dbtype: sqlite
  dsn: "collector-sidecar-server.db"
  maximum-pool-size: 50
  maximum-idle-size: 10

redis:
  enable: false
  address:
  password:
  db: 0
  pool-size: 100
  min-idle-conns: 10
  idle-timeout: 3000

log:
  level: debug
  file-name: web-server.log
  time-format: "2006-01-02 15:04:05.000"
  max-size: 500
  max-backups: 7
  max-age: 7
  compress: true
  local-time: false
  console: true


keycloak:
  realm: ""
  server-url: ""
  client-id: ""
  client-secret: ""